const employeeData = {
  employees: [
    {
      employeeId: 1,
      name: "Sibongile Nkosi",
      position: "Software Engineer",
      department: "Development",
      contact: "sibongile.nkosi@moderntech.com",
      employmentHistory: "Joined in 2015, promoted to Senior in 2018",
      baseSalary: 70000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Present",
        },
        {
          date: "2025-07-26",
          status: "Absent",
        },
        {
          date: "2025-07-27",
          status: "Present",
        },
        {
          date: "2025-07-28",
          status: "Present",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR001",
          type: "Sick Leave",
          startDate: "2025-07-22",
          endDate: "2025-07-22",
          duration: "1 Day",
          reason: "Flu symptoms",
          submitted: "2025-07-21",
          manager: "Busiswa Bala",
          status: "Approved",
        },
        {
          leaveId: "LR002",
          type: "Personal",
          startDate: "2025-12-01",
          endDate: "2025-12-03",
          duration: "3 Days",
          reason: "Family commitment",
          submitted: "2025-11-25",
          manager: "Busiswa Bala",
          status: "Pending",
        },
      ],
      payroll: {
        hoursWorked: 160,
        leaveDeductions: 8,
        finalSalary: 69500,
      },
    },
    {
      employeeId: 2,
      name: "Lungile Moyo",
      position: "HR Manager",
      department: "HR",
      contact: "lungile.moyo@moderntech.com",
      employmentHistory: "Joined in 2013, promoted to Manager in 2017",
      baseSalary: 80000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Present",
        },
        {
          date: "2025-07-26",
          status: "Present",
        },
        {
          date: "2025-07-27",
          status: "Absent",
        },
        {
          date: "2025-07-28",
          status: "Present",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR003",
          type: "Family Responsibility",
          startDate: "2025-07-15",
          endDate: "2025-07-16",
          duration: "2 Days",
          reason: "Family emergency",
          submitted: "2025-07-10",
          manager: "Busiswa Bala",
          status: "Denied",
        },
        {
          leaveId: "LR004",
          type: "Vacation",
          startDate: "2025-12-20",
          endDate: "2025-12-31",
          duration: "12 Days",
          reason: "Annual holiday",
          submitted: "2025-11-30",
          manager: "Busiswa Bala",
          status: "Approved",
        },
      ],

      payroll: {
        hoursWorked: 150,
        leaveDeductions: 10,
        finalSalary: 79000,
      },
    },
    {
      employeeId: 3,
      name: "Thabo Molefe",
      position: "Quality Analyst",
      department: "QA",
      contact: "thabo.molefe@moderntech.com",
      employmentHistory: "Joined in 2018",
      baseSalary: 55000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Present",
        },
        {
          date: "2025-07-26",
          status: "Present",
        },
        {
          date: "2025-07-27",
          status: "Present",
        },
        {
          date: "2025-07-28",
          status: "Absent",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR005",
          type: "Medical Appointment",
          startDate: "2025-07-10",
          endDate: "2025-07-10",
          duration: "1 Day",
          reason: "Dental appointment",
          submitted: "2025-07-08",
          manager: "Busiswa Bala",
          status: "Approved",
        },
        {
          leaveId: "LR006",
          type: "Personal",
          startDate: "2025-12-05",
          endDate: "2025-12-05",
          duration: "1 Day",
          reason: "Private matters",
          submitted: "2025-12-02",
          manager: "Busiswa Bala",
          status: "Pending",
        },
      ],
      payroll: {
        hoursWorked: 170,
        leaveDeductions: 4,
        finalSalary: 54800,
      },
    },
    {
      employeeId: 4,
      name: "Keshav Naidoo",
      position: "Sales Representative",
      department: "Sales",
      contact: "keshav.naidoo@moderntech.com",
      employmentHistory: "Joined in 2020",
      baseSalary: 60000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Absent",
        },
        {
          date: "2025-07-26",
          status: "Present",
        },
        {
          date: "2025-07-27",
          status: "Present",
        },
        {
          date: "2025-07-28",
          status: "Present",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR007",
          type: "Bereavement",
          startDate: "2025-07-20",
          endDate: "2025-07-22",
          duration: "3 Days",
          reason: "Family funeral",
          submitted: "2025-07-18",
          manager: "Busiswa Bala",
          status: "Approved",
        },
        {
          leaveId: "LR008",
          type: "Personal",
          startDate: "2025-12-05",
          endDate: "2025-12-05",
          duration: "1 Day",
          reason: "Private matters",
          submitted: "2025-12-02",
          manager: "Busiswa Bala",
          status: "Pending",
        },
      ],
      payroll: {
        hoursWorked: 165,
        leaveDeductions: 6,
        finalSalary: 59700,
      },
    },
    {
      employeeId: 5,
      name: "Zanele Khumalo",
      position: "Marketing Specialist",
      department: "Marketing",
      contact: "zanele.khumalo@moderntech.com",
      employmentHistory: "Joined in 2019",
      baseSalary: 58000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Present",
        },
        {
          date: "2025-07-26",
          status: "Present",
        },
        {
          date: "2025-07-27",
          status: "Absent",
        },
        {
          date: "2025-07-28",
          status: "Present",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR009",
          type: "Childcare",
          startDate: "2025-12-01",
          endDate: "2025-12-02",
          duration: "2 Days",
          reason: "Looking after sick child",
          submitted: "2025-11-28",
          manager: "Busiswa Bala",
          status: "Pending",
        },
        {
          leaveId: "LR010",
          type: "Personal",
          startDate: "2025-12-05",
          endDate: "2025-12-05",
          duration: "1 Day",
          reason: "Private matters",
          submitted: "2025-12-02",
          manager: "Busiswa Bala",
          status: "Pending",
        },
      ],
      payroll: {
        hoursWorked: 158,
        leaveDeductions: 5,
        finalSalary: 57850,
      },
    },
    {
      employeeId: 6,
      name: "Sipho Zulu",
      position: "UI/UX Designer",
      department: "Design",
      contact: "sipho.zulu@moderntech.com",
      employmentHistory: "Joined in 2016",
      baseSalary: 65000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Present",
        },
        {
          date: "2025-07-26",
          status: "Present",
        },
        {
          date: "2025-07-27",
          status: "Absent",
        },
        {
          date: "2025-07-28",
          status: "Present",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR011",
          type: "Sick Leave",
          startDate: "2025-07-18",
          endDate: "2025-07-19",
          duration: "2 Days",
          reason: "High fever",
          submitted: "2025-07-17",
          manager: "Busiswa Bala",
          status: "Approved",
        },
        {
          leaveId: "LR012",
          type: "Personal",
          startDate: "2025-12-05",
          endDate: "2025-12-05",
          duration: "1 Day",
          reason: "Private matters",
          submitted: "2025-12-02",
          manager: "Busiswa Bala",
          status: "Pending",
        },
      ],
      payroll: {
        hoursWorked: 168,
        leaveDeductions: 2,
        finalSalary: 64800,
      },
    },
    {
      employeeId: 7,
      name: "Naledi Moeketsi",
      position: "DevOps Engineer",
      department: "IT",
      contact: "naledi.moeketsi@moderntech.com",
      employmentHistory: "Joined in 2017",
      baseSalary: 72000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Present",
        },
        {
          date: "2025-07-26",
          status: "Present",
        },
        {
          date: "2025-07-27",
          status: "Present",
        },
        {
          date: "2025-07-28",
          status: "Absent",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR013",
          type: "Vacation",
          startDate: "2025-07-22",
          endDate: "2025-07-26",
          duration: "5 Days",
          reason: "Annual holiday",
          submitted: "2025-07-15",
          manager: "Busiswa Bala",
          status: "Pending",
        },
        {
          leaveId: "LR014",
          type: "Personal",
          startDate: "2025-12-05",
          endDate: "2025-12-05",
          duration: "1 Day",
          reason: "Private matters",
          submitted: "2025-12-02",
          manager: "Busiswa Bala",
          status: "Pending",
        },
      ],
      payroll: {
        hoursWorked: 175,
        leaveDeductions: 3,
        finalSalary: 71800,
      },
    },
    {
      employeeId: 8,
      name: "Farai Gumbo",
      position: "Content Strategist",
      department: "Marketing",
      contact: "farai.gumbo@moderntech.com",
      employmentHistory: "Joined in 2021",
      baseSalary: 56000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Present",
        },
        {
          date: "2025-07-26",
          status: "Absent",
        },
        {
          date: "2025-07-27",
          status: "Present",
        },
        {
          date: "2025-07-28",
          status: "Present",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR015",
          type: "Medical Appointment",
          startDate: "2025-12-02",
          endDate: "2025-12-02",
          duration: "1 Day",
          reason: "Routine medical check-up",
          submitted: "2025-11-29",
          manager: "Busiswa Bala",
          status: "Approved",
        },
        {
          leaveId: "LR016",
          type: "Personal",
          startDate: "2025-12-05",
          endDate: "2025-12-05",
          duration: "1 Day",
          reason: "Private matters",
          submitted: "2025-12-02",
          manager: "Busiswa Bala",
          status: "Pending",
        },
      ],
      payroll: {
        hoursWorked: 160,
        leaveDeductions: 0,
        finalSalary: 56000,
      },
    },
    {
      employeeId: 9,
      name: "Karabo Dlamini",
      position: "Accountant",
      department: "Finance",
      contact: "karabo.dlamini@moderntech.com",
      employmentHistory: "Joined in 2018",
      baseSalary: 62000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Present",
        },
        {
          date: "2025-07-26",
          status: "Present",
        },
        {
          date: "2025-07-27",
          status: "Present",
        },
        {
          date: "2025-07-28",
          status: "Absent",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR017",
          type: "Childcare",
          startDate: "2025-07-19",
          endDate: "2025-07-20",
          duration: "2 Days",
          reason: "Child was unwell",
          submitted: "2025-07-17",
          manager: "Busiswa Bala",
          status: "Denied",
        },
        {
          leaveId: "LR018",
          type: "Personal",
          startDate: "2025-12-05",
          endDate: "2025-12-05",
          duration: "1 Day",
          reason: "Private matters",
          submitted: "2025-12-02",
          manager: "Busiswa Bala",
          status: "Pending",
        },
      ],
      payroll: {
        hoursWorked: 155,
        leaveDeductions: 5,
        finalSalary: 61500,
      },
    },
    {
      employeeId: 10,
      name: "Fatima Patel",
      position: "Customer Support Lead",
      department: "Support",
      contact: "fatima.patel@moderntech.com",
      employmentHistory: "Joined in 2016",
      baseSalary: 58000,
      attendance: [
        {
          date: "2025-07-25",
          status: "Present",
        },
        {
          date: "2025-07-26",
          status: "Present",
        },
        {
          date: "2025-07-27",
          status: "Absent",
        },
        {
          date: "2025-07-28",
          status: "Present",
        },
        {
          date: "2025-07-29",
          status: "Present",
        },
      ],
      leaveRequests: [
        {
          leaveId: "LR019",
          type: "Vacation",
          startDate: "2025-12-03",
          endDate: "2025-12-05",
          duration: "3 Days",
          reason: "Family holiday",
          submitted: "2025-11-27",
          manager: "Busiswa Bala",
          status: "Pending",
        },
        {
          leaveId: "LR020",
          type: "Personal",
          startDate: "2025-12-05",
          endDate: "2025-12-05",
          duration: "1 Day",
          reason: "Private matters",
          submitted: "2025-12-02",
          manager: "Busiswa Bala",
          status: "Pending",
        },
      ],
      payroll: {
        hoursWorked: 162,
        leaveDeductions: 4,
        finalSalary: 57750,
      },
    },
  ],
};
